---
- name: Install required packages
  become: yes
  apt:
    pkg: "{{ query('flattened', [['aptitude'], '{{ packages }}']) }}"
    state: present
  with_flattened:
    - ["aptitude"]
    - "{{ packages }}"

- name: "Do apt {{ apt_upgrade }} upgrade"
  become: yes
  apt:
    update_cache: yes
    upgrade: "{{ apt_upgrade }}"

- name: "Install pip packages"
  become: yes
  pip:
    name: "{{ pip_packages }}"
    executable: "{{ pip_executable }}"
