---
- name: Install required packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_flattened:
    - ["aptitude"]
    - "{{ packages }}"

- name: Do apt safe upgrade
  become: yes
  apt:
    upgrade: full
