---
- name: "Do apt {{ apt_upgrade }} upgrade"
  become: True
  apt:
    force_apt_get: True
    update_cache: True
    upgrade: "{{ apt_upgrade }}"

- name: Install required packages
  become: True
  apt:
    force_apt_get: True
    name: "{{ packages }}"
    state: present

- name: "Install pip packages"
  become: yes
  pip:
    name: "{{ pip_packages }}"
    executable: "{{ pip_executable }}"
